### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by nicholaus12** [HerbFargus/Super-Mario-War#1]
New here and noticed on RetroPie 3.3 that SMW was displaying a couple warnings when launching. Nothing that impacts functionality in any way. The two warnings were about missing image files. I just copy the missing files to the smw directory on every fresh load, but thought I would drop a comment here as well. Sorry if this is the wrong place to do so. The two missing files are:
smw/gfx/packs/Classic/eyecandy/sledgebrothersdead.png
smw/gfx/packs/Classic/menu/menu_vertical_arrows.png

I also uploaded them here.
![sledgebrothersdead](https://cloud.githubusercontent.com/assets/17556605/13411434/9adaffe4-df02-11e5-9a01-75c28c27a7a7.png)
![menu_vertical_arrows](https://cloud.githubusercontent.com/assets/17556605/13411435/9add24cc-df02-11e5-8a94-04b4c90a66df.png)

**Comment by HerbFargus** [comment]
https://github.com/HerbFargus/Super-Mario-War/commit/4dce6e048da9c8fbf0cd56e1409a1a10e25500dd

feel free to compile from source to confirm the additions fixed it. thanks

**Comment by nicholaus12** [comment]
Awesome. You rock. Thank you.
